import assert from "node:assert/strict";
import { afterEach, test } from "node:test";
import { compile, NodeHost } from "@typespec/compiler";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const emitterRoot = packageRoot;
const libraryEntrypoint = join(emitterRoot, "lib/main.tsp").replaceAll("\\", "/");
const temporaryDirectories = [];

afterEach(async () => {
  await Promise.all(temporaryDirectories.splice(0).map((path) => rm(path, { recursive: true, force: true })));
});

async function compileFixture(body) {
  const root = await mkdtemp(join(tmpdir(), "typespec-enum-fixture-"));
  temporaryDirectories.push(root);
  const output = join(root, "output");
  const main = join(root, "main.tsp");
  await writeFile(main, `import ${JSON.stringify(libraryEntrypoint)};\nusing EnumExport;\n${body}`);

  const program = await compile(NodeHost, main, {
    emit: [emitterRoot],
    outputDir: output,
    options: {
      "typespec-enum-plus-emitter": { "emitter-output-dir": output },
    },
  });
  return { output, program };
}

function diagnosticCodes(program) {
  return program.diagnostics.map((diagnostic) => diagnostic.code);
}

test("emits ordered enum-plus modules with custom metadata", async () => {
  const { output, program } = await compileFixture(`
    @exportEnum(#{ domain: "fixture" })
    enum Example {
      @enumItem(#{ label: "后", order: 20 })
      Later: "later",
      @enumItem(#{
        label: "先",
        description: "优先'显示",
        color: "success",
        order: 10,
        disabled: false,
        hidden: true
      })
      First: "first",
      @enumItem(#{ label: "未排序" })
      Unordered: "unordered",
    }

    enum InternalOnly {
      Hidden: "hidden",
    }
  `);

  assert.equal(program.hasError(), false);
  const generated = await readFile(join(output, "fixture.ts"), "utf8");
  assert.ok(generated.indexOf("First:") < generated.indexOf("Later:"));
  assert.ok(generated.indexOf("Later:") < generated.indexOf("Unordered:"));
  assert.match(generated, /description: '优先\\'显示'/);
  assert.match(generated, /color: 'success'/);
  assert.match(generated, /disabled: false/);
  assert.match(generated, /hidden: true/);
  assert.doesNotMatch(generated, /InternalOnly/);
  assert.doesNotMatch(generated, /export type Example =/);
  assert.match(generated, /export type ExampleValue = typeof Example\.valueType/);
  assert.equal(
    await readFile(join(output, "api-types.ts"), "utf8"),
    "// This file is generated bytypespec-enum-plus-emitter. Do not edit.\n\nexport type {\n  ExampleValue as Example,\n} from './fixture'\n",
  );
  assert.equal(
    await readFile(join(output, "index.ts"), "utf8"),
    "// This file is generated bytypespec-enum-plus-emitter. Do not edit.\nexport * from './fixture'\n",
  );
  assert.deepEqual(
    JSON.parse(await readFile(join(output, "enum-manifest.json"), "utf8")),
    {
      version: 2,
      files: ["fixture.ts", "api-types.ts", "index.ts"],
      types: ["Example"],
    },
  );
});

test("emits an empty type list when no enums are exported", async () => {
  const { output, program } = await compileFixture(`
    enum InternalOnly {
      Hidden: "hidden",
    }
  `);

  assert.equal(program.hasError(), false);
  assert.deepEqual(
    JSON.parse(await readFile(join(output, "enum-manifest.json"), "utf8")),
    {
      version: 2,
      files: ["api-types.ts", "index.ts"],
      types: [],
    },
  );
});

test("reports invalid exported enum definitions", async () => {
  const { program } = await compileFixture(`
    @exportEnum(#{ domain: "one" })
    enum InvalidMembers {
      MissingMetadata: "missing",
      @enumItem(#{ label: "Implicit" }) Implicit,
      @enumItem(#{ label: "One" }) One: "duplicate",
      @enumItem(#{ label: "Two" }) Two: "duplicate",
      @enumItem(#{ label: "Number" }) Number: 3,
      @enumItem(#{ label: "中文" }) 中文: "unicode",
    }

    namespace First {
      @exportEnum(#{ domain: "one" })
      enum DuplicateName {
        @enumItem(#{ label: "A" }) A: "a",
      }
    }
    namespace Second {
      @exportEnum(#{ domain: "two" })
      enum DuplicateName {
        @enumItem(#{ label: "B" }) B: "b",
      }
    }
  `);

  const codes = diagnosticCodes(program);
  for (const code of [
    "typespec-enum-plus-emitter/missing-item-metadata",
    "typespec-enum-plus-emitter/implicit-value",
    "typespec-enum-plus-emitter/duplicate-value",
    "typespec-enum-plus-emitter/mixed-value-types",
    "typespec-enum-plus-emitter/invalid-code-name",
    "typespec-enum-plus-emitter/duplicate-export-name",
  ]) {
    assert.ok(codes.includes(code), `missing diagnostic ${code}; received ${codes.join(", ")}`);
  }
});

test("rejects unsafe output domains before emission", async () => {
  const { program } = await compileFixture(`
    @exportEnum(#{ domain: "bad/domain" })
    enum BadDomain {
      @enumItem(#{ label: "A" }) A: "a",
    }
  `);
  assert.ok(diagnosticCodes(program).includes("typespec-enum-plus-emitter/invalid-domain"));
});

test("TypeSpec validates required labels", async () => {
  const { program } = await compileFixture(`
    @exportEnum(#{ domain: "fixture" })
    enum MissingLabel {
      @enumItem(#{} ) Member: "member",
    }
  `);
  assert.ok(program.hasError());
  assert.ok(program.diagnostics.some(
    (diagnostic) => diagnostic.code === "invalid-argument" && diagnostic.message.includes("EnumItemOptions"),
  ));
});

test("rejects reserved domains and generated symbol collisions", async () => {
  for (const domain of ["index", "api-types"]) {
    const { program } = await compileFixture(`
      @exportEnum(#{ domain: "${domain}" })
      enum Example { @enumItem(#{ label: "A" }) A: "a" }
    `);
    assert.ok(diagnosticCodes(program).includes("typespec-enum-plus-emitter/reserved-domain"));
  }
  for (const declarations of [
    'namespace Example { @exportEnum(#{ domain: "one" }) enum Enum { @enumItem(#{ label: "A" }) A: "a" } }',
    `@exportEnum(#{ domain: "one" }) enum Example { @enumItem(#{ label: "A" }) A: "a" }
     @exportEnum(#{ domain: "two" }) enum ExampleValue { @enumItem(#{ label: "B" }) B: "b" }`,
  ]) {
    const { program } = await compileFixture(declarations);
    assert.ok(diagnosticCodes(program).includes("typespec-enum-plus-emitter/generated-name-conflict"));
  }
});

test("escapes control characters and preserves string literals", async () => {
  const { program, output } = await compileFixture(`
    @exportEnum(#{ domain: "escaped" })
    enum Escaped { @enumItem(#{ label: "line\\nnext\\tend" }) Value: "quote'\\\\path" }
  `);
  assert.equal(program.hasError(), false);
  const generated = await readFile(join(output, "escaped.ts"), "utf8");
  assert.ok(generated.includes("label: 'line\\nnext\\tend'"));
  assert.ok(generated.includes("value: 'quote\\'\\\\path'"));
});
