import assert from "node:assert/strict";
import { afterEach, test } from "node:test";
import { compile, NodeHost } from "@typespec/compiler";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { run } from "./helpers.mjs";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const emitterRoot = packageRoot;
const libraryEntrypoint = join(emitterRoot, "lib/main.tsp").replaceAll("\\", "/");
const temporaryDirectories = [];

afterEach(async () => {
  await Promise.all(temporaryDirectories.splice(0).map((path) => rm(path, { recursive: true, force: true })));
});

async function compileFixture(body, emitterOptions = {}) {
  const root = await mkdtemp(join(tmpdir(), "typespec-enum-fixture-"));
  temporaryDirectories.push(root);
  const output = join(root, "output");
  const main = join(root, "main.tsp");
  await writeFile(main, `import ${JSON.stringify(libraryEntrypoint)};\nusing EnumExport;\n${body}`);

  const program = await compile(NodeHost, main, {
    emit: [emitterRoot],
    outputDir: output,
    options: {
      "typespec-enum-plus-emitter": { ...emitterOptions, "emitter-output-dir": output },
    },
  });
  return { output, program };
}

function diagnosticCodes(program) {
  return program.diagnostics.map((diagnostic) => diagnostic.code);
}

test("emits ordered enum-plus modules with custom metadata", async () => {
  const { output, program } = await compileFixture(`
    @exportEnum(#{ domain: "fixture" })
    enum Example {
      @enumItem(#{ label: "后", order: 20 })
      Later: "later",
      @enumItem(#{
        label: "先",
        description: "优先'显示",
        color: "success",
        order: 10,
        disabled: false,
        hidden: true
      })
      First: "first",
      @enumItem(#{ label: "未排序" })
      Unordered: "unordered",
    }

    enum InternalOnly {
      Hidden: "hidden",
    }
  `);

  assert.equal(program.hasError(), false);
  const generated = await readFile(join(output, "fixture.ts"), "utf8");
  assert.ok(generated.indexOf("First:") < generated.indexOf("Later:"));
  assert.ok(generated.indexOf("Later:") < generated.indexOf("Unordered:"));
  assert.match(generated, /description: '优先\\'显示'/);
  assert.match(generated, /color: 'success'/);
  assert.match(generated, /disabled: false/);
  assert.match(generated, /hidden: true/);
  assert.doesNotMatch(generated, /InternalOnly/);
  assert.doesNotMatch(generated, /export type Example =/);
  assert.match(generated, /export type ExampleValue = typeof Example\.valueType/);
  assert.equal(
    await readFile(join(output, "api-types.ts"), "utf8"),
    "// This file is generated by typespec-enum-plus-emitter. Do not edit.\n\nexport type {\n  ExampleValue as Example,\n} from './fixture'\n",
  );
  assert.equal(
    await readFile(join(output, "index.ts"), "utf8"),
    "// This file is generated by typespec-enum-plus-emitter. Do not edit.\nexport * from './fixture'\n",
  );
  assert.deepEqual(
    JSON.parse(await readFile(join(output, "enum-manifest.json"), "utf8")),
    {
      version: 2,
      files: ["fixture.ts", "api-types.ts", "index.ts"],
      types: ["Example"],
    },
  );
});

test("emits an empty type list when no enums are exported", async () => {
  const { output, program } = await compileFixture(`
    enum InternalOnly {
      Hidden: "hidden",
    }
  `);

  assert.equal(program.hasError(), false);
  assert.deepEqual(
    JSON.parse(await readFile(join(output, "enum-manifest.json"), "utf8")),
    {
      version: 2,
      files: ["api-types.ts", "index.ts"],
      types: [],
    },
  );
});

test("reports invalid exported enum definitions", async () => {
  const { program } = await compileFixture(`
    @exportEnum(#{ domain: "one" })
    enum InvalidMembers {
      MissingMetadata: "missing",
      @enumItem(#{ label: "Implicit" }) Implicit,
      @enumItem(#{ label: "One" }) One: "duplicate",
      @enumItem(#{ label: "Two" }) Two: "duplicate",
      @enumItem(#{ label: "Number" }) Number: 3,
      @enumItem(#{ label: "中文" }) 中文: "unicode",
    }

    namespace First {
      @exportEnum(#{ domain: "one" })
      enum DuplicateName {
        @enumItem(#{ label: "A" }) A: "a",
      }
    }
    namespace Second {
      @exportEnum(#{ domain: "two" })
      enum DuplicateName {
        @enumItem(#{ label: "B" }) B: "b",
      }
    }
  `);

  const codes = diagnosticCodes(program);
  for (const code of [
    "typespec-enum-plus-emitter/missing-item-metadata",
    "typespec-enum-plus-emitter/implicit-value",
    "typespec-enum-plus-emitter/duplicate-value",
    "typespec-enum-plus-emitter/mixed-value-types",
    "typespec-enum-plus-emitter/invalid-code-name",
    "typespec-enum-plus-emitter/duplicate-export-name",
  ]) {
    assert.ok(codes.includes(code), `missing diagnostic ${code}; received ${codes.join(", ")}`);
  }
});

test("rejects unsafe output domains before emission", async () => {
  const { program } = await compileFixture(`
    @exportEnum(#{ domain: "bad/domain" })
    enum BadDomain {
      @enumItem(#{ label: "A" }) A: "a",
    }
  `);
  assert.ok(diagnosticCodes(program).includes("typespec-enum-plus-emitter/invalid-domain"));
});

test("TypeSpec validates required labels", async () => {
  const { program } = await compileFixture(`
    @exportEnum(#{ domain: "fixture" })
    enum MissingLabel {
      @enumItem(#{} ) Member: "member",
    }
  `);
  assert.ok(program.hasError());
  assert.ok(program.diagnostics.some(
    (diagnostic) => diagnostic.code === "invalid-argument" && diagnostic.message.includes("EnumItemOptions"),
  ));
});

test("rejects reserved domains and generated symbol collisions", async () => {
  for (const domain of ["index", "api-types"]) {
    const { program } = await compileFixture(`
      @exportEnum(#{ domain: "${domain}" })
      enum Example { @enumItem(#{ label: "A" }) A: "a" }
    `);
    assert.ok(diagnosticCodes(program).includes("typespec-enum-plus-emitter/reserved-domain"));
  }
  for (const declarations of [
    'namespace Example { @exportEnum(#{ domain: "one" }) enum Enum { @enumItem(#{ label: "A" }) A: "a" } }',
    `@exportEnum(#{ domain: "one" }) enum Example { @enumItem(#{ label: "A" }) A: "a" }
     @exportEnum(#{ domain: "two" }) enum ExampleValue { @enumItem(#{ label: "B" }) B: "b" }`,
  ]) {
    const { program } = await compileFixture(declarations);
    assert.ok(diagnosticCodes(program).includes("typespec-enum-plus-emitter/generated-name-conflict"));
  }
});

test("escapes control characters and preserves string literals", async () => {
  const { program, output } = await compileFixture(`
    @exportEnum(#{ domain: "escaped" })
    enum Escaped { @enumItem(#{ label: "line\\nnext\\tend" }) Value: "quote'\\\\path" }
  `);
  assert.equal(program.hasError(), false);
  const generated = await readFile(join(output, "escaped.ts"), "utf8");
  assert.ok(generated.includes("label: 'line\\nnext\\tend'"));
  assert.ok(generated.includes("value: 'quote\\'\\\\path'"));
});


test("export aliases resolve source namespace collisions and update every output", async () => {
  const { output, program } = await compileFixture(`
    namespace Sales {
      @exportEnum(#{ domain: "sales", name: "SalesStatus" })
      enum Status { @enumItem(#{ label: "Open" }) Open: "open" }
    }
    namespace Inventory {
      @exportEnum(#{ domain: "inventory", name: "InventoryStatus" })
      enum Status { @enumItem(#{ label: "Ready" }) Ready: 1 }
    }
    @exportEnum(#{ domain: "legacy", name: "LegacyStatus" })
    enum legacy_status { @enumItem(#{ label: "A" }) A: "a" }
  `);
  assert.equal(program.hasError(), false);
  assert.match(await readFile(join(output, "sales.ts"), "utf8"), /export const SalesStatus = Enum/);
  assert.match(await readFile(join(output, "sales.ts"), "utf8"), /export type SalesStatusValue = typeof SalesStatus.valueType/);
  assert.match(await readFile(join(output, "api-types.ts"), "utf8"), /InventoryStatusValue as InventoryStatus/);
  assert.deepEqual(JSON.parse(await readFile(join(output, "enum-manifest.json"), "utf8")).types,
    ["InventoryStatus", "LegacyStatus", "SalesStatus"]);
});

test("aliases must be valid and cannot collide with generated names", async () => {
  for (const [name, code] of [
    ["bad_name", "invalid-code-name"], ["", "invalid-code-name"],
    ["Enum", "generated-name-conflict"], ["ExistingValue", "generated-name-conflict"],
    ["Existing", "duplicate-export-name"],
  ]) {
    const { program } = await compileFixture(`
      @exportEnum(#{ domain: "one" }) enum Existing { @enumItem(#{ label: "A" }) A: "a" }
      @exportEnum(#{ domain: "two", name: "${name}" }) enum Source { @enumItem(#{ label: "B" }) B: "b" }
    `);
    assert.ok(diagnosticCodes(program).includes(`typespec-enum-plus-emitter/${code}`));
  }
});

test("standalone API types compile without domain modules or enum-plus", async () => {
  const { output, program } = await compileFixture(`
    @exportEnum(#{ domain: "status", name: "ApiStatus" })
    enum Status {
      @enumItem(#{ label: "A" }) A: "active",
      @enumItem(#{ label: "B" }) B: "quote'",
    }
    @exportEnum(#{ domain: "number" })
    enum Priority { @enumItem(#{ label: "N" }) Negative: -1, @enumItem(#{ label: "F" }) Fraction: 1.5 }
    @exportEnum(#{ domain: "empty" }) enum Empty {}
  `, { "api-types-mode": "standalone" });
  assert.equal(program.hasError(), false);
  const apiTypes = await readFile(join(output, "api-types.ts"), "utf8");
  assert.match(apiTypes, /export type ApiStatus = 'active'/);
  assert.match(apiTypes, /export type Priority = -1 \| 1.5/);
  assert.match(apiTypes, /export type Empty = never/);
  assert.doesNotMatch(apiTypes, /import |from /);
  const isolated = await mkdtemp(join(tmpdir(), "standalone-enum-types-"));
  temporaryDirectories.push(isolated);
  await writeFile(join(isolated, "api-types.ts"), apiTypes);
  await writeFile(join(isolated, "usage.ts"), `
    import type { ApiStatus, Priority, Empty } from "./api-types.js";
    const status: ApiStatus = "quote'";
    const priority: Priority = -1;
    // @ts-expect-error unknown string
    const invalid: ApiStatus = "unknown";
    // @ts-expect-error numeric values cannot be strings
    const numeric: Priority = "-1";
    // @ts-expect-error empty enums have no values
    const empty: Empty = 0;
  `);
  const result = run(process.execPath, [join(packageRoot, "node_modules/typescript/bin/tsc"),
    "--noEmit", "--strict", "--module", "NodeNext", "--target", "ES2022", "usage.ts"], isolated);
  assert.equal(result.status, 0, result.stdout + result.stderr);
});

test("standalone empty output is a module and emitter options reject invalid values", async () => {
  const { output, program } = await compileFixture("", { "api-types-mode": "standalone" });
  assert.equal(program.hasError(), false);
  assert.match(await readFile(join(output, "api-types.ts"), "utf8"), /export \{\}/);
  for (const options of [{ "api-types-mode": "invalid" }, { "api-types-mode": true }, { "unknown-option": true }]) {
    const { program } = await compileFixture("", options);
    assert.equal(program.hasError(), true, JSON.stringify(options));
    assert.ok(program.diagnostics.some((diagnostic) => diagnostic.code === "invalid-schema"), JSON.stringify(program.diagnostics.map(({ code, message }) => ({ code, message }))));
  }
});
